"""
============================================================================
STAGE 7 — TRAFFIC SIMULATION (BPR Volume-Delay Model)
============================================================================
Measures how much congestion each intervention REMOVES — turning "we think
this officer placement helps" into "it reduces average delay by X minutes
on the event corridor — measured in simulation."

Model: Bureau of Public Roads (BPR) volume-delay function
  travel_time = free_flow_time × (1 + α × (V/C)^β)
  Standard parameters: α = 0.15, β = 4

Demand model:
  Event crowd → vehicles per hour via car mode share
  Vehicles distributed to segments by hop-weight (closer = more load)

Interventions modelled:
  OFFICER   — junction throughput boost (capacity × 1.3 on incident edges)
  BARRICADE — edge closure (demand reroutes via next-best path)
  DIVERSION — edge penalised (50% demand shifts to alternate route)

Usage:
  sim = EventSimulator(G, seg_info)
  result = sim.evaluate_all(event_spec, footprint_df, candidates)
"""
import numpy as np
import pandas as pd
import networkx as nx

from config import HOP_DECAY, MAX_HOPS, CAPACITY_ADJUSTMENT
from impact import hop_distance_map

# BPR calibration constants (standard traffic engineering values)
BPR_ALPHA = 0.15
BPR_BETA  = 4.0

# Mode share and occupancy
CAR_MODE_SHARE   = 0.35    # fraction of crowd arriving by private car
AVG_OCCUPANCY    = 1.8     # persons per car
EVENT_EGRESS_HR  = 1.5     # vehicles leave over ~1.5 h post-event

# Officer capacity multiplier (signal optimisation lifts throughput ~30%)
OFFICER_CAPACITY_BOOST = 1.30

# Saturation flow: standard 1800 vehicles per hour per lane
SAT_FLOW_VEH_HR_LANE = 1800


class EventSimulator:
    """
    BPR-based simulation. Build once per pipeline run, call evaluate_all()
    for each event to get per-intervention congestion measurements.
    """

    def __init__(self, G, seg_info):
        self.G        = G
        self.seg_info = seg_info
        self._veh_cap = {
            sid: info["lanes"] * SAT_FLOW_VEH_HR_LANE
            for sid, info in seg_info.items()
        }

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------
    def _event_demand(self, crowd):
        """Vehicles per hour generated by the event."""
        return crowd * CAR_MODE_SHARE / AVG_OCCUPANCY / EVENT_EGRESS_HR

    def _distribute_demand(self, junction, total_veh):
        """
        Allocate additional vehicles to segments using hop-decay weights.
        Returns {segment_id: additional_vehicles_per_hour}.
        """
        hop_map   = hop_distance_map(self.G, junction)
        max_cap   = max(s["capacity"] for s in self.seg_info.values()) or 1.0
        weights   = {}
        for sid, info in self.seg_info.items():
            hop = min(hop_map.get(info["u"], 999), hop_map.get(info["v"], 999))
            if hop > MAX_HOPS:
                continue
            w = HOP_DECAY.get(hop, 0.0) * (1 - CAPACITY_ADJUSTMENT * info["capacity"] / max_cap)
            if w > 0:
                weights[sid] = w
        total_w = sum(weights.values()) or 1.0
        return {sid: total_veh * w / total_w for sid, w in weights.items()}

    @staticmethod
    def _bpr_speed(ffs, length_m, volume, capacity_veh):
        """BPR speed given volume and capacity (vehicles/hr)."""
        if capacity_veh <= 0 or length_m <= 0:
            return ffs
        vc = volume / capacity_veh
        t0 = length_m / max(ffs, 1.0)              # relative free-flow time
        t  = t0 * (1.0 + BPR_ALPHA * (vc ** BPR_BETA))
        return float(np.clip(length_m / t, 1.0, ffs * 1.05))

    def _base_volume(self, sid, baseline_speed):
        """Reverse-engineer base traffic volume from BPR given baseline speed."""
        info = self.seg_info[sid]
        ffs  = max(info["ffs"], 1.0)
        cap  = self._veh_cap[sid]
        ratio = ffs / max(baseline_speed, 1.0)
        if ratio <= 1.0:
            return 0.0
        vc = ((ratio - 1.0) / BPR_ALPHA) ** (1.0 / BPR_BETA)
        return float(np.clip(vc * cap, 0.0, cap * 0.95))

    # ------------------------------------------------------------------
    # Footprint-anchored scenario runner
    #
    # The ML model (Stage 6) already predicts the congested speed per segment.
    # The simulation's job is NOT to re-derive congestion from demand — it is
    # to answer: "given this level of congestion, how much does each
    # intervention help?"  We work from the predicted congested speeds and use
    # BPR to compute how a capacity change translates into speed improvement.
    # ------------------------------------------------------------------

    def _congested_speeds_from_footprint(self, footprint_df):
        """
        Return {segment_id: congested_speed_kmh} during the event window.
        congested_speed = baseline_predicted + delta_pred  (delta < 0 → slower)
        """
        agg = (
            footprint_df
            .groupby("segment_id")
            .agg(baseline=("baseline_predicted", "mean"),
                 delta=("delta_pred", "min"))     # worst bin = most congested
            .reset_index()
        )
        agg["congested"] = (agg["baseline"] + agg["delta"]).clip(lower=1.0)
        return agg.set_index("segment_id")["congested"].to_dict()

    def build_segment_baseline(self, footprint_df):
        """
        Extract baseline speed (no-event normal) per segment from footprint.
        Used externally by the optimizer.
        """
        return (
            footprint_df
            .groupby("segment_id")["baseline_predicted"]
            .mean()
            .to_dict()
        )

    def _apply_bpr_improvement(self, sid, congested_speed, cap_multiplier=1.0,
                                demand_fraction=1.0):
        """
        Given a segment's predicted congested speed, compute the new speed
        after an intervention changes its effective capacity.

        Physics: BPR  →  speed_ratio = ffs / speed = 1 + α(V/C)^β
          invert →  V/C = ((speed_ratio − 1) / α)^(1/β)
          apply new C  →  new V/C = (V/C) × (1/cap_multiplier) × demand_fraction
          forward BPR  →  new_speed_ratio = 1 + α(new_V/C)^β
        """
        info = self.seg_info[sid]
        ffs  = max(float(info["ffs"]), 1.0)
        length_m = float(info.get("length_m", 200.0))

        # Infer V/C from congested speed
        speed_ratio = ffs / max(congested_speed, 0.5)
        vc_base     = ((max(speed_ratio - 1.0, 0.0) / BPR_ALPHA) ** (1.0 / BPR_BETA))

        # Apply changes
        vc_new  = vc_base / cap_multiplier * demand_fraction
        t0      = length_m / ffs
        t_new   = t0 * (1.0 + BPR_ALPHA * (vc_new ** BPR_BETA))
        new_spd = (length_m / t_new) if t_new > 0 else ffs
        return float(np.clip(new_spd, 1.0, ffs * 1.05))

    def _build_cap_map(self, interventions):
        """Build {segment_id: (cap_multiplier, demand_fraction)} from an intervention list."""
        cap_map  = {}
        closed   = set()
        diverted = set()

        for iv in interventions:
            if iv["type"] == "officer":
                jn = iv["junction"]
                for u, v in list(self.G.in_edges(jn)) + list(self.G.out_edges(jn)):
                    sid = f"{u}__{v}"
                    if sid in self.seg_info:
                        cur = cap_map.get(sid, (1.0, 1.0))
                        cap_map[sid] = (cur[0] * OFFICER_CAPACITY_BOOST, cur[1])
            elif iv["type"] == "barricade":
                closed.add(iv["segment_id"])
            elif iv["type"] == "diversion":
                diverted.add(iv["segment_id"])

        # Barricade: segment has no traffic; adjacent segments absorb rerouted demand
        for sid in closed:
            cap_map[sid] = (999.0, 0.01)    # near-zero demand on closed segment
            info = self.seg_info.get(sid, {})
            u, v = info.get("u"), info.get("v")
            if u and v:
                try:
                    G_temp = self.G.copy()
                    if G_temp.has_edge(u, v):
                        G_temp.remove_edge(u, v)
                    path = nx.shortest_path(G_temp, u, v, weight="length")
                    for a, b in zip(path[:-1], path[1:]):
                        alt = f"{a}__{b}"
                        if alt in self.seg_info and alt not in closed:
                            cur = cap_map.get(alt, (1.0, 1.0))
                            cap_map[alt] = (cur[0], cur[1] * 1.3)   # 30% more demand
                except Exception:
                    pass

        # Diversion: 50% demand shifts to alternate route
        for sid in diverted:
            cur = cap_map.get(sid, (1.0, 1.0))
            cap_map[sid] = (cur[0], cur[1] * 0.5)
            info = self.seg_info.get(sid, {})
            u, v = info.get("u"), info.get("v")
            if u and v:
                try:
                    G_temp = self.G.copy()
                    if G_temp.has_edge(u, v):
                        G_temp.remove_edge(u, v)
                    path = nx.shortest_path(G_temp, u, v, weight="length")
                    for a, b in zip(path[:-1], path[1:]):
                        alt = f"{a}__{b}"
                        if alt in self.seg_info and alt not in closed:
                            cur = cap_map.get(alt, (1.0, 1.0))
                            cap_map[alt] = (cur[0], cur[1] * 1.15)  # 15% more demand
                except Exception:
                    pass

        return cap_map

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------
    def run_no_intervention(self, event_spec, footprint_df):
        """
        Return congested speed per segment during the event (no intervention).
        Anchored to the ML model's predicted delta — NOT re-derived from demand.
        """
        return self._congested_speeds_from_footprint(footprint_df)

    def run_intervention(self, event_spec, footprint_df, intervention):
        """
        Simulate ONE intervention. Returns improved speed per segment.
        Uses BPR to compute how a capacity change improves the congested state.
        """
        congested = self._congested_speeds_from_footprint(footprint_df)
        cap_map   = self._build_cap_map([intervention])

        speeds = {}
        for sid, info in self.seg_info.items():
            cspd             = congested.get(sid, float(info["ffs"]))
            cap_mult, d_frac = cap_map.get(sid, (1.0, 1.0))
            if cap_mult == 1.0 and d_frac == 1.0:
                speeds[sid] = cspd   # unaffected segment
            else:
                speeds[sid] = self._apply_bpr_improvement(sid, cspd, cap_mult, d_frac)
        return speeds

    def run_combined(self, event_spec, footprint_df, interventions):
        """
        Simulate ALL interventions applied simultaneously (non-additive).
        Combined capacity changes applied in one BPR pass — interactions captured.
        """
        if not interventions:
            return self.run_no_intervention(event_spec, footprint_df)

        congested = self._congested_speeds_from_footprint(footprint_df)
        cap_map   = self._build_cap_map(interventions)

        speeds = {}
        for sid, info in self.seg_info.items():
            cspd             = congested.get(sid, float(info["ffs"]))
            cap_mult, d_frac = cap_map.get(sid, (1.0, 1.0))
            if cap_mult == 1.0 and d_frac == 1.0:
                speeds[sid] = cspd
            else:
                speeds[sid] = self._apply_bpr_improvement(sid, cspd, cap_mult, d_frac)
        return speeds

    def measure_interventions(self, event_spec, footprint_df, candidates):
        """
        Evaluate each candidate intervention individually.

        Returns a DataFrame:
            intervention_type | target | congestion_removed_kmh |
            segments_improved | avg_speed_gain_kmh | combined_rank
        """
        base_speeds = self.run_no_intervention(event_spec, footprint_df)
        affected    = set(footprint_df["segment_id"].unique())

        records = []
        for cand in candidates:
            iv_speeds = self.run_intervention(event_spec, footprint_df, cand)
            gains = []
            for sid in affected:
                b = base_speeds.get(sid, 0.0)
                a = iv_speeds.get(sid, b)
                if a > b:
                    gains.append(a - b)

            records.append({
                "type":                   cand["type"],
                "target":                 cand.get("junction") or cand.get("segment_id"),
                "label":                  cand.get("label", ""),
                "congestion_removed_kmh": round(float(np.mean(gains)) if gains else 0.0, 2),
                "segments_improved":      len(gains),
                "avg_speed_gain_kmh":     round(float(np.sum(gains)  if gains else 0.0), 2),
                "_iv":                    cand,
            })

        df = pd.DataFrame(records)
        if not df.empty:
            df = df.sort_values("congestion_removed_kmh", ascending=False).reset_index(drop=True)
        return df, base_speeds


# ---------------------------------------------------------------------------
# Standalone test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import sys
    from pathlib import Path
    sys.path.insert(0, str(Path(__file__).parent))

    from road_network import build_road_graph
    from data_loader import load_clean_events
    from events_calendar import derive_event_days
    from traffic_data import build_speed_panel
    from features import build_feature_table, split_baseline_data
    from baseline_model import BaselineModel
    from delta import compute_deltas
    from delta_predictor import DeltaPredictor, build_predictor_training_data

    G, seg_info  = build_road_graph()
    events       = load_clean_events(zone_only=True, G=G)
    event_days   = derive_event_days(events, zone_only=True)
    panel        = build_speed_panel(G, seg_info, event_days)
    featured, cats = build_feature_table(panel)
    split        = split_baseline_data(featured)
    bm           = BaselineModel(); bm.train(split, cats)
    panel_d      = compute_deltas(featured, bm)

    train_df = build_predictor_training_data(panel_d, event_days, G, seg_info)
    dp = DeltaPredictor(); dp.train(train_df)

    # Use first event day with a real crowd
    crowd_events = {d: ev for d, ev in event_days.items() if ev["crowd"] > 0}
    date_str, ev = next(iter(crowd_events.items()))
    jn = ev["junction"]

    if jn not in G.nodes:
        print("Junction not in graph — skipping simulation test.")
    else:
        fp = dp.predict_footprint({
            "type": ev["type"], "junction": jn, "crowd": ev["crowd"],
            "start_h": ev["start_h"], "end_h": ev["end_h"],
            "weekday": "Saturday", "is_weekend": True, "is_rain": False,
        }, G, seg_info, bm, cats)

        sim = EventSimulator(G, seg_info)
        print(f"\n[Stage 7] Simulating event at junction {jn} (crowd {ev['crowd']:,})")

        # Sample candidates: officers at the 3 most-impacted junctions
        impacted_nodes = list({seg_info[sid]["u"] for sid in fp["segment_id"].unique()
                                if sid in seg_info})[:3]
        candidates = [{"type": "officer", "junction": n,
                        "label": f"officer@{n}"} for n in impacted_nodes]

        iv_df, base_spd = sim.measure_interventions(
            {"junction": jn, "crowd": ev["crowd"]}, fp, candidates
        )
        print(iv_df[["type","label","congestion_removed_kmh","segments_improved"]])
